App Engineロギングの追加
topgate/goutils pull request #21
Opened 2019-11-15 11:17 UTC by ryutah

## TL;DR
* 構造化ロギングで出力される、App Engineロギングライブラリを追加
* AppEngineコンテキスト生成と、メタデータを取得できるApp Engien共通処理ライブラリを追加

---

とりあえず、 @shigwata さんもレビュアーに入れてみた

close #18

2019-11-18 01:35 UTC, tgoikawa requested changes

2019-11-18 01:35 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +package appengine
file名context.goにしたほうが良いと思う

2019-11-18 01:35 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +package appengine
あと構造化ロギングってapp engineだけでしたっけ？

2019-11-18 01:35 UTC, tgoikawa commented on gcp/appengine/log/log.go
> +
このあたりにフォーマットなしでerrorだけを受け取るError関数ほしい

2019-11-18 01:35 UTC, tgoikawa commented on gcp/appengine/log/log_test.go
> +	// {"logging.googleapis.com/sourceLocation":{"file":"log_test.go","function":"github.com/topgate/goutils/gcp/appengine/log.Example","line":18},"logging.googleapis.com/trace":"projects/sample_project
:+1:

2019-11-18 01:35 UTC, tgoikawa commented on gcp/appengine/export_test.go
> +	ContextKeyTraceID     = contextKeyTraceID
隠蔽せずにわざわざ公開しているのはなぜ？

2019-11-18 01:35 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +	contextKeyTraceID     contextKey = "trace_id"
constではなく
```go
type contextKeyProjectID struct{}
```
にして
取得する時にcontextKeyProjectID{}で取得するようにしたほうがよい

2019-11-18 01:47 UTC, ryutah commented on gcp/appengine/appengine.go
> +package appengine
構造化ロギング自体は、別にApp Engineだけではないんだけど、標準出力をJSONフォーマットで出力したときにStackdriver Loggingにログ流してくれるのはGAEだけだったはず（もしかしたらGKEもかも）

2019-11-18 01:49 UTC, ryutah commented on gcp/appengine/log/log.go
> +
いるかなー？バックトレース出力させるとか、そういう感じの関数？

2019-11-18 01:50 UTC, ryutah commented on gcp/appengine/export_test.go
> +	ContextKeyTraceID     = contextKeyTraceID
テストコードでそのあたりのプライベート定義を使いたいので。テストコードからしか使えないように、ファイル名に `_test` をつけてる感じー

2019-11-18 01:52 UTC, ryutah commented on gcp/appengine/appengine.go
> +	contextKeyTraceID     contextKey = "trace_id"
よくわからん！

2019-11-18 02:00 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +package appengine
なんかGKEでも使えた気がしたのでappengineは適切ではないと思う

2019-11-18 02:02 UTC, tgoikawa commented on gcp/appengine/log/log.go
> +
いや、エラーもみ消すけどログ出力だけしておきたいときとか、毎回 `"%v",err` するのだるいなと感じていた。

2019-11-18 02:02 UTC, tgoikawa commented on gcp/appengine/export_test.go
> +	ContextKeyTraceID     = contextKeyTraceID
あ、_testに定義してる感じか

2019-11-18 02:05 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +	contextKeyTraceID     contextKey = "trace_id"
実装例
```go
type(
	contextKeyProjectID   sturct{}
	contextKeyServiceName struct{}
	contextKeyVersion     struct{}
	contextKeyTraceID     struct{}
)
```

```go
ctx = context.WithValue(ctx, contextKeyProjectID{},os.Getenv("GOOGLE_CLOUD_PROJECT"))
ctx = context.WithValue(ctx, contextKeyServiceName{}, os.Getenv("GAE_SERVICE"))
ctx = context.WithValue(ctx, contextKeyVersion{}, os.Getenv("GAE_VERSION"))
traceID := strings.SplitN(r.Header.Get("X-Cloud-Trace-Context"), "/", 2)[0]
ctx = context.WithValue(ctx, contextKeyTraceID{}, traceID)

```

2019-11-18 03:18 UTC, ryutah commented on gcp/appengine/appengine.go
> +package appengine
外から使うときはApp Engineで使えるやつはappengineパッケージに集まってたほうが使いやすいと思うので、外から利用するパッケージはappengineのままのがよくない？

他環境にも同じ様な処理を書く必要が出てきたら `gcp/internal` パッケージとか切って、そこに共通処理を詰めてく感じにしたほうが、環境ごとの微妙な差分とかを環境ごとに用意したパッケージでうまいこと吸収しながら実装できそう

2019-11-18 03:20 UTC, ryutah commented on gcp/appengine/log/log.go
> +
んー、まあないより合ったほうが便利かもだし追加するかー

2019-11-18 03:38 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +package appengine
`gcp/internal` が外から見えちゃうので気持ち悪い

`gcp/log/structural` あたりがいいのでは

2019-11-18 04:04 UTC, ryutah commented on gcp/appengine/appengine.go
> +package appengine
internalパッケージは外から見えないはず！

https://qiita.com/taka011239@github/items/5735a1ec78bad06f5485

2019-11-18 04:12 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +package appengine
ほーん。 :ok:

2019-11-18 06:51 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +	contextKeyTraceID     contextKey = "trace_id"
@ryutah これ理解しました？

2019-11-18 08:54 UTC, tgoikawa commented on gcp/appengine/appengine.go
> +package appengine
@ryutah あ、file名context.goにしてください

2019-11-18 10:41 UTC, ryutah commented
@tgoikawa 
## fixed
* ログ出力関数として、 `Info` , `Error` 等を追加
* ログ出力のテストケースをついあk

2019-11-18 10:42 UTC, ryutah commented on gcp/appengine/appengine.go
> +package appengine
:done:

2019-11-18 10:42 UTC, ryutah commented on gcp/appengine/log/log.go
> +
:done:

2019-11-18 10:43 UTC, ryutah commented on gcp/appengine/appengine.go
> +	contextKeyTraceID     contextKey = "trace_id"
:done:

2019-11-18 11:37 UTC, tgoikawa approved these changes

2019-11-18 11:38 UTC, tgoikawa commented
GKE用の実装を行なうissue作っておいてください

2019-11-19 04:01 UTC, ryutah commented
@shigwata 使い方とかは旧App Engine SDKとほぼほぼ同じだけど使えそう？

2019-11-19 04:31 UTC, shigwata commented
> @shigwata 使い方とかは旧App Engine SDKとほぼほぼ同じだけど使えそう？

exampleがあるので大丈夫だと思います 👍

2019-11-19 04:59 UTC, merged